---
title: "Calculate differences between scenarios"
author: "Cam Freshwater"
date: "January 30, 2019"
output: html_document
---

This is a quick script that reads in summary data from the main synchrony salmon run and calculates summary statistics (princiaplly % differences in PMs between scenarios) to insert into the main manuscript.

```{r loadData}
require(here); require(tidyverse)

summDat <- read.csv(here("outputs/generatedData", "summaryTable_noSkew.csv")) %>% 
  select(-X)


# Quick helper functions to calc relative difference
relDiff <- function(max, min) {
  (max - min) / max
}

trimDat <- function(oms, vars, synchs = NULL, sigmas = NULL, data) {
  dum <- data %>% 
      filter(om %in% oms, var %in% vars)
  if (!is.null(synchs)) {
    dum <- data %>% 
      filter(om %in% oms, var %in% vars, synch %in% synchs)
  }
  if (!is.null(sigmas)) {
    dum <- data %>% 
      filter(om %in% oms, var %in% vars, sigma %in% sigmas)
  }
  dum %>% 
    select(om, var, sigma, synch, medn)
}

extractVal <- function(data, group){
  if (group == "sigma") {
    dum <- data %>% 
      dplyr::group_by(om, var, sigma) %>% 
      summarize(max = max(medn),
             min = min(medn))
  }
  if (group == "synch") {
    dum <- data %>% 
      dplyr::group_by(om, var, synch) %>%
      summarize(max = max(medn),
             min = min(medn))
  }
  dum
}
```


```{r calcDiffs}
# Declines in agg rec across each sigma treatment
t <- trimDat(oms = "Reference Prod.", vars = "medRecRY", data = summDat)
t2 <- extractVal(t, group = "sigma")
relDiff(t2$max, t2$min)

# Increases in agg rec across sig when synch low
t2 <- extractVal(t, group = "synch") %>% 
  filter(synch == "low")
relDiff(t2$max, t2$min)

# Increases in agg rec across sig when synch low
t <- trimDat(oms = "Reference Prod.", vars = c("ppnCUUpper", "ppnMixedOpen"), 
             data = summDat)
t2 <- extractVal(t, group = "sigma") %>% 
  filter(var == "ppnCUUpper")
relDiff(t2$max, t2$min)
t3 <- extractVal(t, group = "synch") %>% 
  filter(var == "ppnCUUpper")
relDiff(t3$max, t3$min)

t4 <- t %>% 
  filter(var == "ppnMixedOpen")
relDiff(max(t4$avg), min(t4$avg))

# Returns in low vs. ref prod OMs
t <- trimDat(oms = c("Reference Prod.", "Low Prod."), vars = "medRecRY", 
             data = summDat)
t2 <- t %>% 
  filter(sigma == "low", synch == "0.05")
relDiff(max(t2$avg), min(t2$avg))
t2 <- t %>% 
  filter(sigma == "low", 
         !synch == "0.50")
relDiff(max(t2$avg), min(t2$avg))

# Extirpation risk
trimDat(oms = c("Reference Prod.", "Low Prod."), vars = "ppnCUExtant", 
             data = summDat)
trimDat(oms = c("Reference Prod.", "Very Low Prod."), vars = "ppnCUExtant", 
             data = summDat)

# Declines in agg catch across each sigma treatment
t <- trimDat(oms = "Reference Prod.", vars = "medCatch", data = summDat)
t2 <- extractVal(t, group = "sigma")
relDiff(t2$max, t2$min)

# Increases in agg catch across sig when synch low
t2 <- extractVal(t, group = "synch") %>% 
  filter(synch == "0.05")
relDiff(t2$max, t2$min)

# Declines in other catch PMs across each sigma treatment
t <- trimDat(oms = "Reference Prod.", vars = "ppnYrsHighCatch", data = summDat)
relDiff(max(t$medn), min(t$medn))
t <- trimDat(oms = "Reference Prod.", vars = "stabilityCatch", data = summDat)
relDiff(max(t$medn), min(t$medn))

# Increases in agg rec across sig when synch low
t2 <- extractVal(t, group = "synch") %>% 
  filter(synch == "0.05")
relDiff(t2$max, t2$min)

# Returns in low vs. ref prod OMs
t <- trimDat(oms = c("Low Prod."), vars = "medCatch", 
             data = summDat)
relDiff(max(t$medn), min(t$medn))

t <- trimDat(oms = c("Low Prod."), vars = "ppnYrsHighCatch", 
             data = summDat)
relDiff(max(t$medn), min(t$medn))

# Catch stability in low vs low heavy
t <- trimDat(oms = c("Low Prod.", "Low Prod. Heavy Tails"), vars = "stabilityCatch", 
             data = summDat)

```
